(deftheme milan-default
  "Created 2012-03-16.")

(custom-theme-set-variables
 'milan-default
 '(ac-auto-show-menu t)
 '(ac-auto-start t)
 '(ac-dwim t)
 '(ac-modes (quote (emacs-lisp-mode lisp-interaction-mode c-mode cc-mode c++-mode java-mode clojure-mode scala-mode scheme-mode ocaml-mode tuareg-mode perl-mode cperl-mode python-mode ruby-mode ecmascript-mode javascript-mode js-mode js2-mode php-mode css-mode makefile-mode sh-mode fortran-mode f90-mode ada-mode xml-mode sgml-mode org-mode)))
 '(browse-url-browser-function (quote browse-url-firefox))
 '(comint-input-ring-file-name "~/.zsh_history")
 '(custom-menu-nesting 4)
 '(default-input-method nil)
 '(dired-listing-switches "-alh")
 '(enable-recursive-minibuffers t)
 '(erc-header-line-format nil)
 '(erc-mode-hook (quote (erc-add-scroll-to-bottom erc-munge-invisibility-spec erc-move-to-prompt-setup pcomplete-erc-setup erc-button-setup erc-imenu-setup)))
 '(ido-default-buffer-method (quote selected-window))
 '(inferior-lisp-program "sbcl")
 '(max-specpdl-size 2500)
 '(mouse-autoselect-window t)
 '(openwith-associations (quote (("\\.pdf\\'" "mupdf" (file)) ("\\.mp3\\'" "vlc" (file)) ("\\.\\(?:mpe?g\\|avi\\|wmv\\|mp4\\)\\'" "mplayer" ("-idx" file)) ("\\.\\(?:jp?g\\|png\\)\\'" "feh" (file)))))
 '(slime-backend "swank-loader.lisp")
 '(use-file-dialog nil)
 '(user-full-name "Milan")
 '(user-mail-address "milan.santosi@gmail.com")
 '(visible-bell nil)
 '(transient-mark-mode nil)
 '(fringe-mode 0)
 '(erc-track-mode nil)
 '(erc-track-minor-mode t)
 '(desktop-save-mode t)
 '(column-number-mode t)
 '(blink-cursor-mode t))

(custom-theme-set-faces
 'milan-default
 '(ac-completion-face ((t (:foreground "palegreen" :underline t))))
 '(erc-nick-msg-face ((t (:foreground "forest green" :weight bold))))
 '(idle-highlight ((t (:foreground "forest green"))))
 '(smerge-refined-change ((t (:background "black"))))
 '(tabbar-button-face ((t (:inherit tabbar-default-face :foreground "Skyblue"))))
 '(tabbar-default-face ((t (:inherit variable-pitch :background "black" :foreground "gray60" :height 0.8))))
 '(tabbar-selected-face ((t (:inherit tabbar-default-face :background "black" :foreground "limegreen"))))
 '(tabbar-unselected-face ((t (:inherit tabbar-default-face :background "black" :foreground "darkgreen"))))
 '(w3m-tab-background ((((type x w32 mac ns) (class color)) (:background "black" :foreground "green"))))
 '(w3m-tab-mouse ((((type x w32 mac ns) (class color)) (:background "gray10" :foreground "DarkOliveGreen2"))))
 '(w3m-tab-selected ((((type x w32 mac ns) (class color)) (:background "black" :foreground "DarkOrange1" :box (:line-width -1 :style released-button)))))
 '(w3m-tab-unselected ((((type x w32 mac ns) (class color)) (:background "Black" :foreground "Green" :box (:line-width -1 :style released-button)))))
 '(tool-bar ((t (:background "black" :foreground "white" :box (:line-width 1 :style released-button))))))

(provide-theme 'milan-default)
